### ISSUE TITLE
Apple music api gives error.

### ISSUE THREAD

**Issue by tarun57** [mpalazzolo/apple-music-python#1]
I'm trying to create apple music api in python on ubuntu 18.04 but when i'm running .py file it gives error like:
"
15
Traceback (most recent call last):
  File "AppleMusicApi.py", line 1, in <module>
    import applemusicpy
  File "/home/pizone/.local/lib/python2.7/site-packages/applemusicpy/__init__.py", line 1, in <module>
    from .client import AppleMusic
  File "/home/pizone/.local/lib/python2.7/site-packages/applemusicpy/client.py", line 2, in <module>
    import jwt
  File "/home/pizone/.local/lib/python2.7/site-packages/jwt/__init__.py", line 19, in <module>
    from .api_jwt import (
  File "/home/pizone/.local/lib/python2.7/site-packages/jwt/api_jwt.py", line 11, in <module>
    from .api_jws import PyJWS
  File "/home/pizone/.local/lib/python2.7/site-packages/jwt/api_jws.py", line 10, in <module>
    from .algorithms import (
  File "/home/pizone/.local/lib/python2.7/site-packages/jwt/algorithms.py", line 8, in <module>
    from .utils import (
  File "/home/pizone/.local/lib/python2.7/site-packages/jwt/utils.py", line 1, in <module>
    import base64
  File "/usr/lib/python2.7/base64.py", line 98, in <module>
    _urlsafe_encode_translation = string.maketrans(b'+/', b'-_')
AttributeError: 'module' object has no attribute 'maketrans'
"

**Comment by mpalazzolo** [comment]
This seems like a python version issue. I wrote and tested this code with Python 3 and it looks like you are using 2.7. There must be an issue in the PyJWT package. In Python 3, string.maketrans() was deprecated in favor of str.maketrans().

Is it possible for you to run using Python 3 and see if the issue resolves?

**Comment by tarun57** [comment]
Hi mpalazzolo,
when using python3  then the error is 
"
15
Traceback (most recent call last):
  File "AppleMusicApi.py", line 1, in <module>
    import applemusicpy
  File "/home/pizone/.local/lib/python3.6/site-packages/applemusicpy/__init__.py", line 1, in <module>
    from .client import AppleMusic
  File "/home/pizone/.local/lib/python3.6/site-packages/applemusicpy/client.py", line 3, in <module>
    import requests
  File "/home/pizone/.local/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/pizone/.local/lib/python3.6/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/home/pizone/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 3, in <module>
    import logging
  File "/usr/lib/python3.6/logging/__init__.py", line 28, in <module>
    from string import Template
ImportError: cannot import name 'Template'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
    from urllib.request import urlopen
  File "/usr/lib/python3.6/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/lib/python3.6/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.6/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.6/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.6/email/_policybase.py", line 7, in <module>
    from email import header
  File "/usr/lib/python3.6/email/header.py", line 16, in <module>
    import email.quoprimime
  File "/usr/lib/python3.6/email/quoprimime.py", line 44, in <module>
    from string import ascii_letters, digits, hexdigits
ImportError: cannot import name 'ascii_letters'

Original exception was:
Traceback (most recent call last):
  File "AppleMusicApi.py", line 1, in <module>
    import applemusicpy
  File "/home/pizone/.local/lib/python3.6/site-packages/applemusicpy/__init__.py", line 1, in <module>
    from .client import AppleMusic
  File "/home/pizone/.local/lib/python3.6/site-packages/applemusicpy/client.py", line 3, in <module>
    import requests
  File "/home/pizone/.local/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/pizone/.local/lib/python3.6/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/home/pizone/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 3, in <module>
    import logging
  File "/usr/lib/python3.6/logging/__init__.py", line 28, in <module>
    from string import Template
ImportError: cannot import name 'Template'
"

and the pip version is
apple-music-python (1.0.2)

**Comment by mpalazzolo** [comment]
I am not able to reproduce the error, but it seems like there is an issue with the string module. Do you have a file in your current directory named string.py that it is trying to import from instead?

Another suggestion to troubleshoot would be to set up a virtual environment in your project and install the package from there with pip and see if it works. Then we can see if the issue is with the package alone or due to the interaction with the other packages you have installed.

**Comment by mpalazzolo** [comment]
I think the issue might be that you have a file in your directory named string.py that is overriding the default module. Try renaming that and see if it works.

**Comment by tarun57** [comment]
Hi mpalazzolo,
After change string.py file the import "applemusicpy" error solved but now the variable are like 
secret key,keyId, teamid gives error .
when use with python2 the error is:
"Traceback (most recent call last):
  File "AppleMusicApi.py", line 7, in <module>
    am = applemusicpy.AppleMusic(secret_key=secret_key, key_id=key_id, team_id=team_id)
  File "/home/pizone/.local/lib/python2.7/site-packages/applemusicpy/client.py", line 33, in __init__
    self.generate_token(session_length)
  File "/home/pizone/.local/lib/python2.7/site-packages/applemusicpy/client.py", line 55, in generate_token
    'iat': int(datetime.now().timestamp()),  # issued at
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'"




and when using with python3 then error is changed.
"
Traceback (most recent call last):
  File "/home/pizone/.local/lib/python3.6/site-packages/jwt/algorithms.py", line 349, in prepare_key
    key = load_pem_public_key(key, backend=default_backend())
  File "/home/pizone/.local/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 20, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/home/pizone/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1077, in load_pem_public_key
    self._handle_key_loading_error()
  File "/home/pizone/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1335, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AppleMusicApi.py", line 7, in <module>
    am = applemusicpy.AppleMusic(secret_key=secret_key, key_id=key_id, team_id=team_id)
  File "/home/pizone/.local/lib/python3.6/site-packages/applemusicpy/client.py", line 33, in __init__
    self.generate_token(session_length)
  File "/home/pizone/.local/lib/python3.6/site-packages/applemusicpy/client.py", line 58, in generate_token
    token = jwt.encode(payload, self._secret_key, algorithm=self._alg, headers=headers)
  File "/home/pizone/.local/lib/python3.6/site-packages/jwt/api_jwt.py", line 65, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/home/pizone/.local/lib/python3.6/site-packages/jwt/api_jws.py", line 113, in encode
    key = alg_obj.prepare_key(key)
  File "/home/pizone/.local/lib/python3.6/site-packages/jwt/algorithms.py", line 351, in prepare_key
    key = load_pem_private_key(key, password=None, backend=default_backend())
  File "/home/pizone/.local/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/home/pizone/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1051, in load_pem_private_key
    password,
  File "/home/pizone/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1277, in _load_key
    self._handle_key_loading_error()
  File "/home/pizone/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1335, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
"

**Comment by mpalazzolo** [comment]
For the Python 2 error, there is no timestamp() function in the datetime package. That was added in Python 3. I would recommend using this package in Python 3 only.

For the second error, there might be an issue with how you formatted you secret key in your code. I would recommend storing it in a separate file exactly how you got it from Apple (not included in your git repo), and read it in with something like this:
`with open(file_location, 'r') as f:`
`    secret_key = f.read()`

**Comment by tarun57** [comment]
Its working now mpalazzolo with python3 
but api status 401
here is my code
"
import applemusicpy

with open('/opt/Python/AuthKey_34MTF92235.p8') as f:
	secret_key = f.read()
key_id = '****'
team_id = '****'

am = applemusicpy.AppleMusic(secret_key=secret_key, key_id=key_id, team_id=team_id)
print(am)
results = am.search('travis scott', types=['albums'], limit=5)
for item in results['results']['albums']['data']:
    print(item['attributes']['name'])
""

and the result is 
"
<applemusicpy.client.AppleMusic object at 0x7fb27f0b4438>
Traceback (most recent call last):
  File "AppleMusicApi.py", line 11, in <module>
    results = am.search('travis scott', types=['albums'], limit=5)
  File "/home/pizone/.local/lib/python3.6/site-packages/applemusicpy/client.py", line 715, in search
    return self._get(url, term=term, l=l, limit=limit, offset=offset, types=type_str)
  File "/home/pizone/.local/lib/python3.6/site-packages/applemusicpy/client.py", line 107, in _get
    return self._call('GET', url, kwargs)
  File "/home/pizone/.local/lib/python3.6/site-packages/applemusicpy/client.py", line 92, in _call
    r.raise_for_status()  # Check for error
  File "/home/pizone/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.music.apple.com/v1/catalog/us/search?term=travis%2Bscott&limit=5&types=albums
""

I want to create an api  that is use in ionic in which user will login with apple credentials and then get genres of that user and all playlist and songs that will stream.

**Comment by mpalazzolo** [comment]
You are setting your key ID and team ID to blank strings. Also this API does not require user credentials to work as it is just gets catalog resources. I suggest read through the API documentation to understand how it works: https://developer.apple.com/documentation/applemusicapi
